version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: TitoliDiBorsa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 18032002
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
    networks:
      - local


networks:
  local:
